const witness0: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1RecordBindingResult = {"bound":true}; // JobMarketIntelligenceAdapterRecordV1RecordBindingResult
const witness1: {} extends Pick<import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1RecordBindingResult, "bound"> ? false : true = true;
const witness2: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1RecordBindingResult["bound"] = null; // bound: not nullable
const witness3: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1TypeAdmissionResult = {"admitted":true}; // JobMarketIntelligenceAdapterRecordV1TypeAdmissionResult
const witness4: {} extends Pick<import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1TypeAdmissionResult, "admitted"> ? false : true = true;
const witness5: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1TypeAdmissionResult["admitted"] = null; // admitted: not nullable
const witness6: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1 = {"contractId":"job-market-intelligence-adapter-record.v1","jmiRecordRef":"features/resolve-market-signals.feature","jmiRecordType":"job-market-intelligence-state.v1","jmiRecordDigest":"sha256:40c49cfd3fe8f4b201a7742d867db97ac270214d593372c8b19d15c15b4cc141","adapterAuthorityId":"sidefx-jmi-adapter-authority.v1","adapterAuthorityDigest":"sha256:3a4fb77d237ae56da1c6762ba4387403c35224980d3995907fd87443b0d82de1","observedWindow":"2026-01-01/2026-08-18","adaptationDisposition":"ADAPTED_EVIDENCE_BINDING","findingCodes":[],"adapterReceiptDigest":"sha256:1778c6cea17361c878efa00a01bcf2ac500fe31784ab710c08b64e54d3612111"}; // JobMarketIntelligenceAdapterRecordV1
const witness7: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1["contractId"] = "job-market-intelligence-adapter-record.v1"; // contractId: admitted literal
const witness8: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1["contractId"] = "__outside_declared_literals__"; // contractId: closed literal
const witness9: {} extends Pick<import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1, "contractId"> ? false : true = true;
const witness10: {} extends Pick<import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1, "jmiRecordRef"> ? false : true = true;
const witness11: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1["jmiRecordRef"] = null; // jmiRecordRef: not nullable
const witness12: {} extends Pick<import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1, "jmiRecordType"> ? false : true = true;
const witness13: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1["jmiRecordType"] = null; // jmiRecordType: not nullable
const witness14: {} extends Pick<import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1, "jmiRecordDigest"> ? false : true = true;
const witness15: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1["jmiRecordDigest"] = null; // jmiRecordDigest: not nullable
const witness16: {} extends Pick<import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1, "adapterAuthorityId"> ? false : true = true;
const witness17: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1["adapterAuthorityId"] = null; // adapterAuthorityId: not nullable
const witness18: {} extends Pick<import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1, "adapterAuthorityDigest"> ? false : true = true;
const witness19: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1["adapterAuthorityDigest"] = null; // adapterAuthorityDigest: not nullable
const witness20: {} extends Pick<import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1, "observedWindow"> ? false : true = true;
const witness21: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1["observedWindow"] = null; // observedWindow: not nullable
const witness22: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1["adaptationDisposition"] = "ADAPTED_EVIDENCE_BINDING"; // adaptationDisposition: admitted literal
const witness23: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1["adaptationDisposition"] = "ADAPTATION_HELD"; // adaptationDisposition: admitted literal
const witness24: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1["adaptationDisposition"] = "__outside_declared_literals__"; // adaptationDisposition: closed literal
const witness25: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1["findingCodes"] = null; // findingCodes: not nullable
const witness26: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1["adapterReceiptDigest"] = null; // adapterReceiptDigest: not nullable
const witness27: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1["recordBindingResult"] = null; // recordBindingResult: not nullable
const witness28: import("../body/contracts/index.js").JobMarketIntelligenceAdapterRecordV1["typeAdmissionResult"] = null; // typeAdmissionResult: not nullable
