import type { AdmittedCanonicalCircuitBlueprintV1PayloadObligationRecordConformance } from "./admitted-canonical-circuit-blueprint-v1-payload-obligation-record-conformance.js";
import type { AdmittedCanonicalCircuitBlueprintV1PayloadObligationRecordGeometry } from "./admitted-canonical-circuit-blueprint-v1-payload-obligation-record-geometry.js";
import type { AdmittedCanonicalCircuitBlueprintV1PayloadObligationRecordReview } from "./admitted-canonical-circuit-blueprint-v1-payload-obligation-record-review.js";

// Projected from kernel/schemas/https://schemas.agentic-harness.local/contracts/admitted-canonical-circuit-blueprint.v1.schema.json/properties/payload/properties/obligationRecord.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface AdmittedCanonicalCircuitBlueprintV1PayloadObligationRecord {
  "conformance": AdmittedCanonicalCircuitBlueprintV1PayloadObligationRecordConformance;
  "geometry": AdmittedCanonicalCircuitBlueprintV1PayloadObligationRecordGeometry;
  "review": AdmittedCanonicalCircuitBlueprintV1PayloadObligationRecordReview;
}
