// Projected from kernel/schemas/https://schemas.agentic-harness.local/contracts/canonical-blueprint-admission-request.v1.schema.json/properties/payload.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalBlueprintAdmissionRequestV1Payload {
  "capabilityId": string;
  "featureDigest": string;
  "featureScenarioCount": number;
  "candidateBytesBase64": string;
  "conformanceEvidenceBytesBase64": string;
  "geometryProofBytesBase64": string;
  "reviewReceiptBytesBase64": string;
  "reviewBoundaryBytesBase64": string;
  "projectionReceiptBytesBase64": string;
  "reviewTestimonyBytesBase64": string;
  "canonicalSchemaBytesBase64": string;
  "candidate"?: unknown;
  "candidateCarrierDigest"?: unknown;
  "conformanceEvidence"?: unknown;
  "conformanceEvidenceDigest"?: unknown;
  "geometryProof"?: unknown;
  "geometryProofDigest"?: unknown;
  "reviewReceipt"?: unknown;
  "reviewReceiptDigest"?: unknown;
  "reviewBoundary"?: unknown;
  "reviewBoundaryDigest"?: unknown;
  "projectionReceipt"?: unknown;
  "projectionReceiptDigest"?: unknown;
  "reviewTestimony"?: unknown;
  "reviewTestimonyDigest"?: unknown;
  "canonicalSchemaDigest"?: unknown;
  "admissionRequest"?: unknown;
  "require-blueprint-conformance-evidenceDisposition"?: unknown;
  "require-blueprint-geometry-proofDisposition"?: unknown;
  "require-current-approved-review-receiptDisposition"?: unknown;
}
