// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json/properties/capability.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1Capability {
  "capabilityId": string;
  "version": string;
  "rootExperience": string;
  "capabilityAuthorityDigest"?: string;
  "capsuleDigest"?: string;
}
