import type { CanonicalCircuitBlueprintV1NodeCellEnergizedAuthorityRef } from "./canonical-circuit-blueprint-v1-node-cell-energized-authority-ref.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json#/$defs/cell/properties/energized.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1NodeCellEnergized {
  "identity": string;
  "authority": CanonicalCircuitBlueprintV1NodeCellEnergizedAuthorityRef;
}
