import type { CanonicalCircuitBlueprintV1EdgeAuthorityRef } from "./canonical-circuit-blueprint-v1-edge-authority-ref.js";
import type { CanonicalCircuitBlueprintV1EdgeBoundedReturn } from "./canonical-circuit-blueprint-v1-edge-bounded-return.js";
import type { CanonicalCircuitBlueprintV1EdgeEdgeObservabilityObligation } from "./canonical-circuit-blueprint-v1-edge-edge-observability-obligation.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json#/$defs/edge.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1Edge {
  "edgeId": string;
  "from": string;
  "to": string;
  "topology": "TRANSITION" | "BRANCH_ROUTE" | "FAN_OUT_MEMBER" | "CONVERGENCE_REQUIREMENT" | "ALTITUDE_DESCENT" | "BOUNDED_RETURN";
  "semanticPrecedence": "REQUIRED" | "INDEPENDENT";
  "projectionOrdinal": number;
  "bindingAuthority": CanonicalCircuitBlueprintV1EdgeAuthorityRef;
  "contractRelation"?: "SATISFIES" | "REQUIRES";
  "semanticProgress"?: "NARROWS" | "ESTABLISHES" | "TERMINATES" | "DESCENDS" | "BOUNDED_RETURN";
  "selectingVariant"?: string;
  "boundedReturn"?: CanonicalCircuitBlueprintV1EdgeBoundedReturn;
  "fanOutSetId"?: string;
  "observability"?: CanonicalCircuitBlueprintV1EdgeEdgeObservabilityObligation;
}
