import type { CanonicalCircuitBlueprintV1EdgeEdgeObservabilityObligationAuthorityRef } from "./canonical-circuit-blueprint-v1-edge-edge-observability-obligation-authority-ref.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json#/$defs/edgeObservabilityObligation.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1EdgeEdgeObservabilityObligation {
  "checkpoints": (string)[];
  "authority": CanonicalCircuitBlueprintV1EdgeEdgeObservabilityObligationAuthorityRef;
}
