import type { CanonicalCircuitBlueprintV1ServiceLevelItemsAuthorityRef } from "./canonical-circuit-blueprint-v1-service-level-items-authority-ref.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json/properties/serviceLevel/properties/crossApplyParity/items.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1ServiceLevelItems {
  "targetId": string;
  "preservedIdentities": (string)[];
  "correlationRuleRef"?: CanonicalCircuitBlueprintV1ServiceLevelItemsAuthorityRef;
}
