import type { CanonicalCircuitBlueprintV1NodeCellFirstAuthorityRef } from "./canonical-circuit-blueprint-v1-node-cell-first-authority-ref.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json#/$defs/cell/properties/first.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1NodeCellFirst {
  "identity": string;
  "contract": CanonicalCircuitBlueprintV1NodeCellFirstAuthorityRef;
}
