import type { LiveEquityPriceRequestV1Payload } from "./live-equity-price-request-v1-payload.js";

export const CONTRACT_ID = "live-equity-price-request.v1" as const;

// Projected from kernel/schemas/https://schemas.sidefx.local/contracts/live-equity-price-request.v1.schema.json.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface LiveEquityPriceRequestV1 {
  "contractId": "live-equity-price-request.v1";
  "payload": LiveEquityPriceRequestV1Payload;
}
