// Projected from kernel/schemas/https://schemas.agentic-harness.local/contracts/equity-market-price-evidence.v1.schema.json/properties/providerTestimony.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface EquityMarketPriceEvidenceV1ProviderTestimony {
  "bindingId": string;
  "providerId": string;
  "nativeShape"?: "quoteSummary.result.0.price" | "quoteResponse.result.0";
}
