// Projected from kernel/schemas/https://schemas.agentic-harness.local/contracts/native-equity-market-price-testimony.v1.schema.json.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface NativeEquityMarketPriceTestimonyV1 {

}
