export const CONTRACT_ID = "native-equity-market-price-testimony-rejection.v1" as const;
export const DISPOSITION = "NATIVE_MARKET_PRICE_TESTIMONY_REJECTED" as const;
export const REASON_CODE = "REQUIRED_NATIVE_FIELDS_ABSENT" as const;

// Projected from kernel/schemas/https://schemas.agentic-harness.local/contracts/native-equity-market-price-testimony-rejection.v1.schema.json.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface NativeEquityMarketPriceTestimonyRejectionV1 {
  "contractId": "native-equity-market-price-testimony-rejection.v1";
  "disposition": "NATIVE_MARKET_PRICE_TESTIMONY_REJECTED";
  "reasonCode": "REQUIRED_NATIVE_FIELDS_ABSENT";
  "absentFieldCount"?: number;
  "providerTestimony"?: Record<string, unknown>;
}
