// Projected from kernel/schemas/https://schemas.agentic-harness.local/contracts/equity-market-price-evidence.v1.schema.json/properties/payload.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface EquityMarketPriceEvidenceV1Payload {
  "symbol": string;
  "region": string;
  "currency": string;
  "observedPrice": number;
  "observedMarketTime": number;
  "marketState": string;
  "exchange": string;
  "sourceAttribution": string;
}
