// Projected from kernel/schemas/https://schemas.agentic-harness.local/contracts/equity-market-price-evidence-request.v1.schema.json/properties/payload/properties/providerBinding.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface EquityMarketPriceEvidenceRequestV1PayloadProviderBinding {
  "bindingId": string;
  "providerId": string;
}
