export const CONTRACT_ID = "equity-market-price-provider-unavailable.v1" as const;
export const DISPOSITION = "EQUITY_MARKET_PRICE_PROVIDER_UNAVAILABLE" as const;

// Projected from kernel/schemas/https://schemas.agentic-harness.local/contracts/equity-market-price-provider-unavailable.v1.schema.json.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface EquityMarketPriceProviderUnavailableV1 {
  "contractId": "equity-market-price-provider-unavailable.v1";
  "disposition": "EQUITY_MARKET_PRICE_PROVIDER_UNAVAILABLE";
  "providerAttemptEvidence"?: Record<string, unknown>;
}
