import type { SidefxSemanticProviderResolutionV1Finding } from "./sidefx-semantic-provider-resolution-v1-finding.js";
import type { SidefxSemanticProviderResolutionV1Items } from "./sidefx-semantic-provider-resolution-v1-items.js";

export const RESOLUTION_TYPE = "sidefx-semantic-provider-resolution.v1" as const;

// Projected from kernel/schemas/https://schemas.agentic-harness.local/sidefx/sidefx-semantic-provider-resolution.schema.json.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface SidefxSemanticProviderResolutionV1 {
  "resolutionType": "sidefx-semantic-provider-resolution.v1";
  "disposition": "PROVIDERS_RESOLVED" | "NOT_OBSERVABLE";
  "snapshotDigest": string;
  "requestedPlatformCapabilityId": string;
  "requestedTarget": string;
  "providers": (SidefxSemanticProviderResolutionV1Items)[];
  "consideredCount": number;
  "eligibleCount": number;
  "findings": (SidefxSemanticProviderResolutionV1Finding)[];
  "resolutionDigest": string;
}
