import type { SidefxProviderResolutionRequestV1ItemsItems } from "./sidefx-provider-resolution-request-v1-items-items.js";

// Projected from kernel/schemas/https://schemas.agentic-harness.local/sidefx/sidefx-provider-resolution-request.schema.json/properties/providerBindings/items.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface SidefxProviderResolutionRequestV1Items {
  "providerBindingRef": string;
  "providerBindingDigest": string;
  "providerAuthorityId": string;
  "providerAuthorityRef": string;
  "providerAuthorityDigest": string;
  "platformCapabilityId": string;
  "lifecycle": string;
  "conformanceDisposition": string;
  "conformanceReceiptRef": string;
  "conformanceReceiptDigest": string;
  "authorityBindings": (SidefxProviderResolutionRequestV1ItemsItems)[];
  "declaredTargets": (string)[];
}
