// Projected from kernel/schemas/https://schemas.agentic-harness.local/sidefx/sidefx-semantic-common.schema.json#/$defs/sourcePosition.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface SidefxSemanticProviderResolutionV1FindingSourcePosition {
  "line": number;
  "column": number;
  "byteOffset": number;
}
