// Projected from kernel/schemas/https://schemas.agentic-harness.local/sidefx/sidefx-semantic-provider-resolution.schema.json/properties/providers/items/properties/authorityBindings/items.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface SidefxSemanticProviderResolutionV1ItemsItems {
  "bindingId": string;
  "sourceRef": string;
  "sourceDigest": string;
}
