import type { SidefxProviderResolutionRequestV1Items } from "./sidefx-provider-resolution-request-v1-items.js";

export const CONTRACT_ID = "sidefx-provider-resolution-request.v1" as const;
export const EVALUATION_BOUNDARY = "NON_PRODUCTION_WAVE3_SPECIALIST_ASK" as const;

// Projected from kernel/schemas/https://schemas.agentic-harness.local/sidefx/sidefx-provider-resolution-request.schema.json.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface SidefxProviderResolutionRequestV1 {
  "contractId": "sidefx-provider-resolution-request.v1";
  "evaluationBoundary": "NON_PRODUCTION_WAVE3_SPECIALIST_ASK";
  "snapshotDigest": string;
  "requestedPlatformCapabilityId": string;
  "requestedTarget": string;
  "conformantDispositions": (string)[];
  "providerBindings": (SidefxProviderResolutionRequestV1Items)[];
}
