import type { JobMarketIntelligenceAdapterRecordV1RecordBindingResult } from "./job-market-intelligence-adapter-record-v1-record-binding-result.js";
import type { JobMarketIntelligenceAdapterRecordV1TypeAdmissionResult } from "./job-market-intelligence-adapter-record-v1-type-admission-result.js";

export const CONTRACT_ID = "job-market-intelligence-adapter-record.v1" as const;

// Projected from kernel/schemas/https://schemas.agentic-harness.local/adapt-job-market-intelligence-evidence/record.schema.json.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface JobMarketIntelligenceAdapterRecordV1 {
  "contractId": "job-market-intelligence-adapter-record.v1";
  "jmiRecordRef": string;
  "jmiRecordType": string;
  "jmiRecordDigest": string;
  "adapterAuthorityId": string;
  "adapterAuthorityDigest": string;
  "observedWindow": string;
  "adaptationDisposition"?: "ADAPTED_EVIDENCE_BINDING" | "ADAPTATION_HELD";
  "findingCodes"?: (string)[];
  "adapterReceiptDigest"?: string;
  "recordBindingResult"?: JobMarketIntelligenceAdapterRecordV1RecordBindingResult;
  "typeAdmissionResult"?: JobMarketIntelligenceAdapterRecordV1TypeAdmissionResult;
}
