import type { CanonicalCircuitBlueprintV1ProjectionAuthoritiesAuthorityRef } from "./canonical-circuit-blueprint-v1-projection-authorities-authority-ref.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json/properties/projectionAuthorities.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1ProjectionAuthorities {
  "profiles": CanonicalCircuitBlueprintV1ProjectionAuthoritiesAuthorityRef[];
  "views": unknown[];
}
