// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json#/$defs/sliDefinition.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1ServiceLevelSliDefinition {
  "sliId": string;
  "testimonyInputs": string[];
  "scope": string;
  "calculation": string;
  "window": string;
  "freshness": string;
  "unit": string;
  "missingTestimonyDisposition": unknown;
  "dimensions"?: string[];
}
