import type { CanonicalCircuitBlueprintV1NodeObservabilityContractSamplingAuthorityRef } from "./canonical-circuit-blueprint-v1-node-observability-contract-sampling-authority-ref.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json#/$defs/observabilityContract/properties/sampling.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1NodeObservabilityContractSampling {
  "strategy": unknown;
  "rate"?: number;
  "conditionRef"?: CanonicalCircuitBlueprintV1NodeObservabilityContractSamplingAuthorityRef;
}
