import type { CanonicalCircuitBlueprintV1ServiceLevelSlaBoundaryAuthorityRef } from "./canonical-circuit-blueprint-v1-service-level-sla-boundary-authority-ref.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json#/$defs/slaBoundary.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1ServiceLevelSlaBoundary {
  "slaId": string;
  "authority": CanonicalCircuitBlueprintV1ServiceLevelSlaBoundaryAuthorityRef;
  "serviceBoundary": unknown;
  "sloIds"?: string[];
}
