import type { CanonicalCircuitBlueprintV1NodeObservabilityContractAuthorityRef } from "./canonical-circuit-blueprint-v1-node-observability-contract-authority-ref.js";
import type { CanonicalCircuitBlueprintV1NodeObservabilityContractItems } from "./canonical-circuit-blueprint-v1-node-observability-contract-items.js";
import type { CanonicalCircuitBlueprintV1NodeObservabilityContractSampling } from "./canonical-circuit-blueprint-v1-node-observability-contract-sampling.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json#/$defs/observabilityContract.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1NodeObservabilityContract {
  "checkpoints": string[];
  "semanticAddress": string;
  "causalAddress": string;
  "measurements": CanonicalCircuitBlueprintV1NodeObservabilityContractItems[];
  "authorizedDimensions": string[];
  "sampling": CanonicalCircuitBlueprintV1NodeObservabilityContractSampling;
  "evidenceDestination": string;
  "authority": CanonicalCircuitBlueprintV1NodeObservabilityContractAuthorityRef;
}
