import type { CanonicalBlueprintAdmissionRequestV1Payload } from "./canonical-blueprint-admission-request-v1-payload.js";

export const CONTRACT_ID = "canonical-blueprint-admission-request.v1" as const;

// Projected from kernel/schemas/https://schemas.agentic-harness.local/contracts/canonical-blueprint-admission-request.v1.schema.json.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalBlueprintAdmissionRequestV1 {
  "payload": CanonicalBlueprintAdmissionRequestV1Payload;
}
