import type { EquityMarketPriceEvidenceRequestV1PayloadProviderBinding } from "./equity-market-price-evidence-request-v1-payload-provider-binding.js";

// Projected from kernel/schemas/https://schemas.agentic-harness.local/contracts/equity-market-price-evidence-request.v1.schema.json/properties/payload.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface EquityMarketPriceEvidenceRequestV1Payload {
  "nativeTestimony": Record<string, unknown>;
  "region": string;
  "providerBinding": EquityMarketPriceEvidenceRequestV1PayloadProviderBinding;
}
