import type { EquityMarketPriceEvidenceV1Payload } from "./equity-market-price-evidence-v1-payload.js";
import type { EquityMarketPriceEvidenceV1ProviderTestimony } from "./equity-market-price-evidence-v1-provider-testimony.js";

export const CONTRACT_ID = "equity-market-price-evidence.v1" as const;

// Projected from kernel/schemas/https://schemas.agentic-harness.local/contracts/equity-market-price-evidence.v1.schema.json.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface EquityMarketPriceEvidenceV1 {
  "contractId": "equity-market-price-evidence.v1";
  "disposition": "EQUITY_MARKET_PRICE_EVIDENCE_RESOLVED" | "NATIVE_MARKET_PRICE_TESTIMONY_REJECTED" | "EQUITY_MARKET_PRICE_PROVIDER_UNAVAILABLE";
  "providerTestimony": EquityMarketPriceEvidenceV1ProviderTestimony;
  "payload"?: EquityMarketPriceEvidenceV1Payload;
  "reasonCode"?: "REQUIRED_NATIVE_FIELDS_ABSENT" | "PROVIDER_EXCHANGE_NOT_COMPLETED";
  "absentFieldCount"?: number;
}
