import type { EquityMarketPriceEvidenceRequestV1Payload } from "./equity-market-price-evidence-request-v1-payload.js";

export const CONTRACT_ID = "equity-market-price-evidence-request.v1" as const;

// Projected from kernel/schemas/https://schemas.agentic-harness.local/contracts/equity-market-price-evidence-request.v1.schema.json.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface EquityMarketPriceEvidenceRequestV1 {
  "contractId": "equity-market-price-evidence-request.v1";
  "payload": EquityMarketPriceEvidenceRequestV1Payload;
}
