// Projected from kernel/schemas/https://schemas.sidefx.local/contracts/live-equity-price-request.v1.schema.json/properties/payload.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface LiveEquityPriceRequestV1Payload {
  "symbol": string;
  "region": "US";
}
