import type { CanonicalCircuitBlueprintV1NodeCellEnergized } from "./canonical-circuit-blueprint-v1-node-cell-energized.js";
import type { CanonicalCircuitBlueprintV1NodeCellFirst } from "./canonical-circuit-blueprint-v1-node-cell-first.js";
import type { CanonicalCircuitBlueprintV1NodeCellResult } from "./canonical-circuit-blueprint-v1-node-cell-result.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json#/$defs/cell.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1NodeCell {
  "first": CanonicalCircuitBlueprintV1NodeCellFirst;
  "energized": CanonicalCircuitBlueprintV1NodeCellEnergized;
  "result": CanonicalCircuitBlueprintV1NodeCellResult;
}
