import type { CanonicalCircuitBlueprintV1SourceAuthorityAuthorityRef } from "./canonical-circuit-blueprint-v1-source-authority-authority-ref.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json/properties/sourceAuthority.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1SourceAuthority {
  "disposition": unknown;
  "lineage": CanonicalCircuitBlueprintV1SourceAuthorityAuthorityRef[];
  "featureAuthorityRef"?: CanonicalCircuitBlueprintV1SourceAuthorityAuthorityRef;
}
