import type { CanonicalCircuitBlueprintV1EdgeAuthorityRef } from "./canonical-circuit-blueprint-v1-edge-authority-ref.js";
import type { CanonicalCircuitBlueprintV1EdgeBoundedReturn } from "./canonical-circuit-blueprint-v1-edge-bounded-return.js";
import type { CanonicalCircuitBlueprintV1EdgeEdgeObservabilityObligation } from "./canonical-circuit-blueprint-v1-edge-edge-observability-obligation.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json#/$defs/edge.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1Edge {
  "edgeId": string;
  "from": string;
  "to": string;
  "topology": unknown;
  "semanticPrecedence": unknown;
  "projectionOrdinal": number;
  "bindingAuthority": CanonicalCircuitBlueprintV1EdgeAuthorityRef;
  "contractRelation"?: unknown;
  "semanticProgress"?: unknown;
  "selectingVariant"?: string;
  "boundedReturn"?: CanonicalCircuitBlueprintV1EdgeBoundedReturn;
  "fanOutSetId"?: string;
  "observability"?: CanonicalCircuitBlueprintV1EdgeEdgeObservabilityObligation;
}
