import type { SidefxSemanticProviderResolutionV1ItemsItems } from "./sidefx-semantic-provider-resolution-v1-items-items.js";

// Projected from kernel/schemas/https://schemas.agentic-harness.local/sidefx/sidefx-semantic-provider-resolution.schema.json/properties/providers/items.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface SidefxSemanticProviderResolutionV1Items {
  "providerBindingRef": string;
  "providerBindingDigest": string;
  "providerAuthorityId": string;
  "providerAuthorityRef": string;
  "providerAuthorityDigest": string;
  "platformCapabilityId": string;
  "lifecycle": string;
  "conformanceDisposition": string;
  "conformanceReceiptRef": string;
  "conformanceReceiptDigest": string;
  "authorityBindings": SidefxSemanticProviderResolutionV1ItemsItems[];
  "eligibilityDisposition": unknown;
  "reasonCode": string;
}
