// Projected from kernel/schemas/https://schemas.agentic-harness.local/sidefx/sidefx-provider-resolution-request.schema.json/properties/providerBindings/items/properties/authorityBindings/items.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface SidefxProviderResolutionRequestV1ItemsItems {
  "bindingId": string;
  "sourceRef": string;
  "sourceDigest": string;
}
