import type { SidefxSemanticProviderResolutionV1FindingSourcePosition } from "./sidefx-semantic-provider-resolution-v1-finding-source-position.js";

// Projected from kernel/schemas/https://schemas.agentic-harness.local/sidefx/sidefx-semantic-common.schema.json#/$defs/finding.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface SidefxSemanticProviderResolutionV1Finding {
  "code": string;
  "severity": unknown;
  "message": string;
  "sourceRef": string;
  "sourcePointer": string;
  "ruleId"?: string;
  "start"?: SidefxSemanticProviderResolutionV1FindingSourcePosition;
  "end"?: SidefxSemanticProviderResolutionV1FindingSourcePosition;
  "relatedSourcePointers"?: string[];
}
