import type { CanonicalCircuitBlueprintV1ServiceLevelSloDefinitionAuthorityRef } from "./canonical-circuit-blueprint-v1-service-level-slo-definition-authority-ref.js";
import type { CanonicalCircuitBlueprintV1ServiceLevelSloDefinitionItems } from "./canonical-circuit-blueprint-v1-service-level-slo-definition-items.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json#/$defs/sloDefinition.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1ServiceLevelSloDefinition {
  "sloId": string;
  "sliId": string;
  "target": string;
  "evaluationWindow": string;
  "errorBudgetPolicy": CanonicalCircuitBlueprintV1ServiceLevelSloDefinitionAuthorityRef;
  "childAllocations"?: (CanonicalCircuitBlueprintV1ServiceLevelSloDefinitionItems)[];
}
