import type { AdmittedCanonicalCircuitBlueprintV1PayloadAdmissionEvidence } from "./admitted-canonical-circuit-blueprint-v1-payload-admission-evidence.js";
import type { AdmittedCanonicalCircuitBlueprintV1PayloadItems } from "./admitted-canonical-circuit-blueprint-v1-payload-items.js";
import type { AdmittedCanonicalCircuitBlueprintV1PayloadObligationRecord } from "./admitted-canonical-circuit-blueprint-v1-payload-obligation-record.js";
import type { CanonicalCircuitBlueprintV1 } from "./canonical-circuit-blueprint-v1.js";

export const BLUEPRINT_ROUTE_DISPOSITION = "CLOSED" as const;

// Projected from kernel/schemas/https://schemas.agentic-harness.local/contracts/admitted-canonical-circuit-blueprint.v1.schema.json/properties/payload.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface AdmittedCanonicalCircuitBlueprintV1Payload {
  "disposition": "BLUEPRINT_AUTHORITY_ADMITTED" | "BLUEPRINT_ADMISSION_REJECTED";
  "blueprint": (CanonicalCircuitBlueprintV1) | null;
  "blueprintAuthorityDigest": string;
  "candidateCarrierDigest": string;
  "admittedCarrierDigest": (string) | null;
  "admissionEvidence": AdmittedCanonicalCircuitBlueprintV1PayloadAdmissionEvidence;
  "obligationRecord": AdmittedCanonicalCircuitBlueprintV1PayloadObligationRecord;
  "findings": (AdmittedCanonicalCircuitBlueprintV1PayloadItems)[];
  "blueprintRouteDisposition": "CLOSED";
}
