import type { CanonicalCircuitBlueprintV1StructuralMappingC4MappingAuthorityRef } from "./canonical-circuit-blueprint-v1-structural-mapping-c4-mapping-authority-ref.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json#/$defs/c4Mapping.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1StructuralMappingC4Mapping {
  "elementId": string;
  "realizationAuthority": CanonicalCircuitBlueprintV1StructuralMappingC4MappingAuthorityRef;
  "nodeIds"?: (string)[];
}
