// Projected from kernel/schemas/https://schemas.agentic-harness.local/contracts/admitted-canonical-circuit-blueprint.v1.schema.json/properties/payload/properties/obligationRecord/properties/review.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface AdmittedCanonicalCircuitBlueprintV1PayloadObligationRecordReview {

}
