// Projected from kernel/schemas/https://schemas.agentic-harness.local/contracts/blueprint-admission-obligation-disposition.v1.schema.json/properties/payload.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface BlueprintAdmissionObligationDispositionV1Payload {

}
