import type { CanonicalCircuitBlueprintV1BlueprintAuthority } from "./canonical-circuit-blueprint-v1-blueprint-authority.js";
import type { CanonicalCircuitBlueprintV1Capability } from "./canonical-circuit-blueprint-v1-capability.js";
import type { CanonicalCircuitBlueprintV1Edge } from "./canonical-circuit-blueprint-v1-edge.js";
import type { CanonicalCircuitBlueprintV1Node } from "./canonical-circuit-blueprint-v1-node.js";
import type { CanonicalCircuitBlueprintV1ProjectionAuthorities } from "./canonical-circuit-blueprint-v1-projection-authorities.js";
import type { CanonicalCircuitBlueprintV1ServiceLevel } from "./canonical-circuit-blueprint-v1-service-level.js";
import type { CanonicalCircuitBlueprintV1SourceAuthority } from "./canonical-circuit-blueprint-v1-source-authority.js";
import type { CanonicalCircuitBlueprintV1StructuralMapping } from "./canonical-circuit-blueprint-v1-structural-mapping.js";

export const CARRIER_VERSION = "canonical-circuit-blueprint.v1" as const;

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1 {
  "capability": CanonicalCircuitBlueprintV1Capability;
  "sourceAuthority": CanonicalCircuitBlueprintV1SourceAuthority;
  "blueprintAuthority": CanonicalCircuitBlueprintV1BlueprintAuthority;
  "nodes": CanonicalCircuitBlueprintV1Node[];
  "edges": CanonicalCircuitBlueprintV1Edge[];
  "projectionAuthorities": CanonicalCircuitBlueprintV1ProjectionAuthorities;
  "$schema"?: string;
  "structuralMapping"?: CanonicalCircuitBlueprintV1StructuralMapping;
  "serviceLevel"?: CanonicalCircuitBlueprintV1ServiceLevel;
}
