import type { CanonicalCircuitBlueprintV1StructuralMappingC4Mapping } from "./canonical-circuit-blueprint-v1-structural-mapping-c4-mapping.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json/properties/structuralMapping.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1StructuralMapping {
  "context": CanonicalCircuitBlueprintV1StructuralMappingC4Mapping;
  "container": CanonicalCircuitBlueprintV1StructuralMappingC4Mapping;
  "component": CanonicalCircuitBlueprintV1StructuralMappingC4Mapping;
  "code"?: CanonicalCircuitBlueprintV1StructuralMappingC4Mapping;
}
