// Projected from kernel/schemas/https://schemas.agentic-harness.local/contracts/admitted-canonical-circuit-blueprint.v1.schema.json/properties/payload/properties/obligationRecord.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface AdmittedCanonicalCircuitBlueprintV1PayloadObligationRecord {
  "conformance": Record<string, unknown>;
  "geometry": Record<string, unknown>;
  "review": Record<string, unknown>;
}
