import type { AdmittedCanonicalCircuitBlueprintV1Payload } from "./admitted-canonical-circuit-blueprint-v1-payload.js";

export const CONTRACT_ID = "admitted-canonical-circuit-blueprint.v1" as const;

// Projected from kernel/schemas/https://schemas.agentic-harness.local/contracts/admitted-canonical-circuit-blueprint.v1.schema.json.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface AdmittedCanonicalCircuitBlueprintV1 {
  "contractId": "admitted-canonical-circuit-blueprint.v1";
  "payload": AdmittedCanonicalCircuitBlueprintV1Payload;
}
