// Projected from kernel/schemas/https://schemas.agentic-harness.local/contracts/blueprint-admission-obligation-disposition.v1.schema.json.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface BlueprintAdmissionObligationDispositionV1 {
  "contractId": string;
  "payload": Record<string, unknown>;
}
