import type { CanonicalCircuitBlueprintV1EdgeBoundedReturnAuthorityRef } from "./canonical-circuit-blueprint-v1-edge-bounded-return-authority-ref.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json#/$defs/edge/properties/boundedReturn.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1EdgeBoundedReturn {
  "kind": "REPAIR" | "RESUMPTION" | "ITERATION";
  "bound": number;
  "authority": CanonicalCircuitBlueprintV1EdgeBoundedReturnAuthorityRef;
}
