// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json#/$defs/observabilityContract/properties/measurements/items.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1NodeObservabilityContractItems {
  "measurementId": string;
  "unit": string;
}
