import type { CanonicalCircuitBlueprintV1ServiceLevelItems } from "./canonical-circuit-blueprint-v1-service-level-items.js";
import type { CanonicalCircuitBlueprintV1ServiceLevelSlaBoundary } from "./canonical-circuit-blueprint-v1-service-level-sla-boundary.js";
import type { CanonicalCircuitBlueprintV1ServiceLevelSliDefinition } from "./canonical-circuit-blueprint-v1-service-level-sli-definition.js";
import type { CanonicalCircuitBlueprintV1ServiceLevelSloDefinition } from "./canonical-circuit-blueprint-v1-service-level-slo-definition.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json/properties/serviceLevel.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1ServiceLevel {
  "indicators": (CanonicalCircuitBlueprintV1ServiceLevelSliDefinition)[];
  "objectives": (CanonicalCircuitBlueprintV1ServiceLevelSloDefinition)[];
  "agreements"?: (CanonicalCircuitBlueprintV1ServiceLevelSlaBoundary)[];
  "crossApplyParity"?: (CanonicalCircuitBlueprintV1ServiceLevelItems)[];
}
