import type { CanonicalCircuitBlueprintV1NodeCell } from "./canonical-circuit-blueprint-v1-node-cell.js";
import type { CanonicalCircuitBlueprintV1NodeObservabilityContract } from "./canonical-circuit-blueprint-v1-node-observability-contract.js";
import type { CanonicalCircuitBlueprintV1NodeProviderSlot } from "./canonical-circuit-blueprint-v1-node-provider-slot.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json#/$defs/node.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1Node {
  "nodeId": string;
  "kind": "state" | "responsibility" | "outcome" | "junction" | "convergence" | "provider-slot" | "terminal";
  "altitude": "CAPABILITY" | "OPERATION" | "MECHANIC" | "PROVIDER";
  "projectionOrdinal": number;
  "cell"?: CanonicalCircuitBlueprintV1NodeCell;
  "requiredProducts"?: (string)[];
  "terminalDisposition"?: string;
  "providerSlot"?: CanonicalCircuitBlueprintV1NodeProviderSlot;
  "observability"?: CanonicalCircuitBlueprintV1NodeObservabilityContract;
}
