import type { CanonicalCircuitBlueprintV1ServiceLevelSloDefinitionItemsAuthorityRef } from "./canonical-circuit-blueprint-v1-service-level-slo-definition-items-authority-ref.js";

// Projected from kernel/schemas/https://agentic-harness.local/contracts/canonical-circuit-blueprint.v1.schema.json#/$defs/sloDefinition/properties/childAllocations/items.
// GENERATED by tools/src/projection/providers/node/structural-projection-provider.ts — do not hand-edit.
export interface CanonicalCircuitBlueprintV1ServiceLevelSloDefinitionItems {
  "nodeId": string;
  "allocation": string;
  "authority": CanonicalCircuitBlueprintV1ServiceLevelSloDefinitionItemsAuthorityRef;
}
